services:
  backend:
    command: sh -c "npm run migration:run && npm run start"
    environment:
      FRONTEND_URL: https://bluepeak-capital.online
      FRONTEND_URLS: https://bluepeak-capital.online

  frontend:
    environment:
      NEXT_PUBLIC_SITE_URL: https://bluepeak-capital.online
      NEXT_PUBLIC_API_URL: https://bluepeak-capital.online
