import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialSchema1722600000000 implements MigrationInterface {
  name = 'InitialSchema1722600000000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"');
    await queryRunner.query(`CREATE TYPE user_role AS ENUM ('USER','ADMIN','SUPER_ADMIN')`);
    await queryRunner.query(`CREATE TYPE user_status AS ENUM ('PENDING_VERIFICATION','ACTIVE','SUSPENDED','BLOCKED')`);
    await queryRunner.query(`CREATE TYPE deposit_status AS ENUM ('PENDING','APPROVED','REJECTED','CANCELLED')`);
    await queryRunner.query(`CREATE TYPE crypto_network AS ENUM ('BEP20','TRC20')`);
    await queryRunner.query(`CREATE TYPE investment_status AS ENUM ('PENDING','ACTIVE','PAUSED','COMPLETED','CANCELLED')`);
    await queryRunner.query(`CREATE TYPE profit_status AS ENUM ('PENDING','CREDITED','FAILED','REVERSED')`);
    await queryRunner.query(`CREATE TYPE withdrawal_status AS ENUM ('PENDING','APPROVED','PROCESSING','PAID','REJECTED','CANCELLED')`);
    await queryRunner.query(`CREATE TYPE transaction_type AS ENUM ('DEPOSIT_APPROVED','INVESTMENT_CREATED','PROFIT_CREDITED','WITHDRAWAL_RESERVED','WITHDRAWAL_PAID','WITHDRAWAL_REJECTED','REFERRAL_COMMISSION','REVERSAL')`);
    await queryRunner.query(`CREATE TABLE users (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), email text UNIQUE NOT NULL, "passwordHash" text NOT NULL, "fullName" text NOT NULL, "phoneNumber" text, role user_role NOT NULL DEFAULT 'USER', status user_status NOT NULL DEFAULT 'PENDING_VERIFICATION', "referralCode" text UNIQUE NOT NULL, "referredByUserId" text, "emailVerified" boolean NOT NULL DEFAULT false, "phoneVerified" boolean NOT NULL DEFAULT false, "availableBalance" numeric(18,2) NOT NULL DEFAULT 0, "reservedBalance" numeric(18,2) NOT NULL DEFAULT 0, "investmentBalance" numeric(18,2) NOT NULL DEFAULT 0, "totalProfit" numeric(18,2) NOT NULL DEFAULT 0, "totalReferralEarnings" numeric(18,2) NOT NULL DEFAULT 0, "totalWithdrawn" numeric(18,2) NOT NULL DEFAULT 0, "lastLoginAt" timestamptz, "mustChangePassword" boolean NOT NULL DEFAULT false, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now())`);
    await queryRunner.query(`CREATE TABLE deposits (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "userId" text NOT NULL, amount numeric(18,2) NOT NULL, currency text NOT NULL DEFAULT 'USD', "paymentMethod" text NOT NULL DEFAULT 'CRYPTO', "paymentNetwork" crypto_network NOT NULL, "transactionReference" text NOT NULL, "paymentProofUrl" text, status deposit_status NOT NULL DEFAULT 'PENDING', "rejectionReason" text, "reviewedByUserId" text, "approvedAt" timestamptz, "rejectedAt" timestamptz, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now())`);
    await queryRunner.query(`CREATE TABLE investments (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "userId" text NOT NULL, "depositId" text UNIQUE NOT NULL, "principalAmount" numeric(18,2) NOT NULL, "weeklyReturnPercentage" numeric(7,4) NOT NULL, "weeklyProfitAmount" numeric(18,2) NOT NULL, "totalProfitEarned" numeric(18,2) NOT NULL DEFAULT 0, "startDate" timestamptz NOT NULL, "nextProfitDate" timestamptz NOT NULL, "lastProfitDate" timestamptz, status investment_status NOT NULL DEFAULT 'ACTIVE', "statusReason" text, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now())`);
    await queryRunner.query(`CREATE TABLE profits (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "userId" text NOT NULL, "investmentId" text NOT NULL, "principalAmount" numeric(18,2) NOT NULL, "profitPercentage" numeric(7,4) NOT NULL, "profitAmount" numeric(18,2) NOT NULL, "scheduledDate" timestamptz NOT NULL, "creditedAt" timestamptz, status profit_status NOT NULL DEFAULT 'PENDING', "failureReason" text, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now(), UNIQUE ("investmentId", "scheduledDate"))`);
    await queryRunner.query(`CREATE TABLE withdrawals (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "userId" text NOT NULL, amount numeric(18,2) NOT NULL, "feeAmount" numeric(18,2) NOT NULL DEFAULT 0, "netAmount" numeric(18,2) NOT NULL, network crypto_network NOT NULL, "walletAddress" text NOT NULL, status withdrawal_status NOT NULL DEFAULT 'PENDING', "rejectionReason" text, "reviewedByUserId" text, "paidAt" timestamptz, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now())`);
    await queryRunner.query(`CREATE TABLE transactions (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "userId" text NOT NULL, type transaction_type NOT NULL, amount numeric(18,2) NOT NULL, status text NOT NULL DEFAULT 'POSTED', "referenceId" text, "createdAt" timestamptz NOT NULL DEFAULT now())`);
    await queryRunner.query(`CREATE TABLE wallet_addresses (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "userId" text NOT NULL, network crypto_network NOT NULL, address text NOT NULL, active boolean NOT NULL DEFAULT true, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now())`);
    await queryRunner.query(`CREATE TABLE referral_commissions (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "referrerUserId" text NOT NULL, "referredUserId" text NOT NULL, "depositId" text NOT NULL, amount numeric(18,2) NOT NULL, reversed boolean NOT NULL DEFAULT false, "createdAt" timestamptz NOT NULL DEFAULT now())`);
    await queryRunner.query(`CREATE TABLE notifications (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "userId" text NOT NULL, title text NOT NULL, body text NOT NULL, read boolean NOT NULL DEFAULT false, "createdAt" timestamptz NOT NULL DEFAULT now())`);
    await queryRunner.query(`CREATE TABLE system_settings (key text PRIMARY KEY, value jsonb NOT NULL, "updatedAt" timestamptz NOT NULL DEFAULT now())`);
    await queryRunner.query(`CREATE TABLE audit_logs (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "actorUserId" text, action text NOT NULL, "entityType" text NOT NULL, "entityId" text, metadata jsonb NOT NULL DEFAULT '{}', "createdAt" timestamptz NOT NULL DEFAULT now())`);
    await queryRunner.query(`CREATE TABLE auth_sessions (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "userId" text NOT NULL, "refreshTokenHash" text NOT NULL, "ipAddress" text, "userAgent" text, "expiresAt" timestamptz NOT NULL, "revokedAt" timestamptz, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now())`);
    await queryRunner.query(`CREATE TABLE password_reset_tokens (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "userId" text NOT NULL, "tokenHash" text NOT NULL, "expiresAt" timestamptz NOT NULL, "usedAt" timestamptz, "createdAt" timestamptz NOT NULL DEFAULT now())`);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE IF EXISTS password_reset_tokens, auth_sessions, audit_logs, system_settings, notifications, referral_commissions, wallet_addresses, transactions, withdrawals, profits, investments, deposits, users');
    await queryRunner.query('DROP TYPE IF EXISTS transaction_type, withdrawal_status, profit_status, investment_status, crypto_network, deposit_status, user_status, user_role');
  }
}
